# Generated by Django 3.2.7 on 2021-09-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('describe', models.TextField()),
                ('followers', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Videoinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=200)),
                ('video_view', models.CharField(max_length=200)),
                ('publish_date', models.CharField(max_length=200)),
                ('likes', models.CharField(max_length=200)),
                ('coins', models.CharField(max_length=200)),
                ('collects', models.CharField(max_length=200)),
                ('brief', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=200)),
                ('cover', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videopage.author')),
            ],
        ),
    ]
